/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/****LCD FUNCTIONS******
 *
 *	STEPS TO USE LCD FUNCTIONS
 *	STEP1. LCD_INIT();
 *	STEP2. ANY LCD FUNCTIONS CAN BE USED MENTIONED IN LCD.H
 */
#include "lcd.h"
#include <stdio.h>
#include "delay.h"
int main(void)
{
	 char buf[100];
	 char Input_str[]="The value is";	//Insert your string to be displayed.
	 char Input_sample[]="HI HOW ARE U?";
	 int Input_data=100;

	//-------------to display string on LCD--------------------------
	LCD_INIT();
	LCD_SEND_STRING(Input_sample);
	LCD_ROLLING_DISP_RIGHT(1);	//Produces rolling display continuously to right

	//--------To send sensor data / variable data with string on LCD-------------------
	LCD_DISPLAY_CLEAR();
			//User String & Data Format specifiers & variables..
	sprintf(buf,"%s  %d",Input_str,Input_data);
	LCD_SEND_STRING(buf);
	LCD_ROLLING_DISP_LEFT(2); 	//change to 0-254 for fixed rolling disp or 255 to get continuous rolling display
								//But,if 255 used then,ensure that ROLLING_DISP function is called at last in the program

}
